version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      ci:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /test
    schedule:
      interval: weekly
